### ISSUE TITLE
Migrate from MariaDB to CouchDB

### ISSUE THREAD

**Issue by eatingzhang0611** [Inventory-Squad/inventory#128]
**As a** developer
**I need** to use couchDB
**So that** I can use service on cloud.

**Assumptions:** 
* Using CouchDB.
* Using IBM cloud.

**Acceptance Criteria:**
```
Given I want to deploy my application to dev space
When I push my code with couchDB
Then all build tests should pass. 
```

**Comment by faberald** [comment]
Here we need to 
* update Travis
* update model
* update service
* update test

**Comment by faberald** [comment]
Error throw when initial the db:
```
Traceback (most recent call last):
  File "/vagrant/tests/test_inventory.py", line 41, in setUp
    Inventory.init_db(app)
  File "/vagrant/service/models.py", line 324, in init_db
    Inventory.database = Inventory.client[dbname]
  File "/usr/local/lib/python3.6/dist-packages/cloudant/client.py", line 399, in __getitem__
    if db.exists():
  File "/usr/local/lib/python3.6/dist-packages/cloudant/database.py", line 130, in exists
    resp = self.r_session.head(self.database_url)
  File "/usr/local/lib/python3.6/dist-packages/cloudant/database.py", line 93, in database_url
    self._database_host, url_quote_plus(self.database_name)))
  File "/usr/lib/python3.6/urllib/parse.py", line 841, in quote_plus
    string = quote(string, safe + space, encoding, errors)
  File "/usr/lib/python3.6/urllib/parse.py", line 825, in quote
    return quote_from_bytes(string, safe)
  File "/usr/lib/python3.6/urllib/parse.py", line 850, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
-------------------- >> begin captured logging << --------------------
flask.app: INFO: VCAP_SERVICES is undefined.
flask.app: INFO: Cloudant Endpoint: http://localhost:5984/
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost
urllib3.connectionpool: DEBUG: http://localhost:5984 "POST /_session HTTP/1.1" 200 46
```

The Sprint 3 is close to its end, we might need to close this issue and open another one to fix this issue in Sprint 4.

**Comment by eatingzhang0611** [comment]
Did you try the code from lab-bdd?

**Comment by eatingzhang0611** [comment]
Found the error, wrong parameter for 
`def setUp(self):
        """ Runs before each test """
        Inventory.init_db(app)
        Inventory.remove_all()`
Should use string instead of app. 
Closing the issue and will fix errors in the next sprint.

**Comment by eatingzhang0611** [comment]
Close the issue because the sprint is approaching to its end.
Will continue working in #129

**Comment by eatingzhang0611** [comment]
Close the issue because the sprint is approaching to its end.
Will continue working in #129
